php:
    build: ./php/
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./public_html:/var/www/html
    links:
        - mysql

mysql:
    image: mysql:latest
    volumes:
        - "./mysql:/var/lib/mysql"
        - ".:/home/docker"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: banco_base
        MYSQL_USER: project
        MYSQL_PASSWORD: project

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
