php:
    build: ./php/
    ports:
    - "80:80"
    - "443:443"
    links:
        - mysql
    volumes_from:
        - app

app:
    image: php:5.6-apache
    volumes:
        - ./public_html:/var/www/html
    command: "true"

mysql:
    image: mysql:latest
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: banco_base
        MYSQL_USER: project
        MYSQL_PASSWORD: project

data:
    image: mysql:latest
    volumes:
        - "./mysql:/var/lib/mysql"
        - ".:/home/docker"
    command: "true"

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
